alias tr='tree -I ".git|node_modules|dist" -a .'
alias ls='ls --color'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias e='explorer.exe'
alias g='git'
alias h='hx'
alias b='cd ..'
alias lg='lazygit'
alias ff='fastfetch'
alias s='spf'
alias j='just'
# alias t='tmux'
alias update='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'
alias reload='exec zsh'
alias usage='du -h --max-depth=1 | sort -h'
