inherits = "melange"
# inherits = "rose_pine_moon"
# inherits = "catppuccin_macchiato"
# inherits = "tokyonight"
# inherits = "nord-night"
# inherits = "gruvbox_dark_hard"
# inherits = "test"

"ui.background" = {}
"ui.popup" = {}
"ui.popup.info" = {}
"ui.bufferline.background" = {}
"ui.bufferline" = { }
"ui.statusline" = {}
"ui.text" = {}
"ui.menu" = {}
